chat/urls.py
from django.urls import path
from .views import chat_room

app_name = 'chat'

urlpatterns = [
    path('chat/', chat_room, name='chat_room'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('order_create/', views.OrderCreateView.as_view(), name='order_create'),
    path('order_success/', views.SuccessTemplateView.as_view(), name='order_success'),
    path('order_canceled/', views.CanceledTemplateView.as_view(), name='order_canceled'),
    path('', views.OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order'),
]

programming_guide/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('languages.urls', 'languages')),
    path('users/', include('users.urls', 'users')),
    path('comments/', include('comments.urls', 'comments')),
    path('basket/', include('basket.urls', 'basket')),
    path('opinions/', include('opinions.urls', 'opinions')),
    path('chat/', include('chat.urls', 'chat')),
    path('paid_lessons/', include('paid_lessons.urls', 'paid_lessons')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

from paid_lessons.models import PaidLesson
from users.models import User
from paid_card.models import PaidCard


class Order(models.Model):
    CREATED = 0
    PAID = 1
    STATUSES = (
        (CREATED, 'Created'),
        (PAID, 'Paid'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    paid_card_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)  # WYBORKA
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Order #{self.id}. {self.first_name} {self.last_name}'

    def update_after_payment(self):
        paid_cards = PaidCard.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.paid_card_history = {
            'purchased_items': [paid_card.de_json() for paid_card in paid_cards],
            'total_sum': float(paid_cards.price_all_products()),
        }
        paid_cards.delete()
        self.save()

orders/forms.py
from urllib import request

from django import forms
from orders.models import Order
from users.models import User


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'name'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'sername'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'email'}))


    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email')

orders/views.py
import stripe
from django.http import HttpResponse
from http import HTTPStatus
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from stripe.error import SignatureVerificationError
from orders.models import Order
from programming_guide.settings import DOMAIN_NAME, STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET
from paid_card.models import PaidCard
from orders.forms import OrderForm

stripe.api_key = STRIPE_SECRET_KEY


class SuccessTemplateView(TemplateView):
    template_name = 'orders/success.html'
    title = 'Thank you for order'


class CanceledTemplateView(TemplateView):
    template_name = 'orders/canceled.html'


class OrderListView(ListView):
    template_name = 'orders/orders.html'
    title = 'PrGuide - Orders'
    queryset = Order.objects.all()
    ordering = ('-created')

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Store - Order #{self.object.id}'
        return context


class OrderCreateView(CreateView):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')
    title = 'Create order'

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(request, *args, **kwargs)
        paid_cards = PaidCard.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=paid_cards.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(DOMAIN_NAME, reverse('orders:order_canceled'))
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user  # form -> method OBJECT instance -> our initiator -> taken OUR request.user
        return super(OrderCreateView, self).form_valid(form)  # edit method super, override super for our class


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None
    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        # Retrieve the session. If you require line items in the response, you may include them by expanding line_items.
        session = event['data']['object']
        # Fulfill the purchase...
        fulfill_order(session)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()


orders/templates/orders/canceled.html
<!DOCTYPE html>
<html>
<head>
    <title>Checkout canceled</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
</section>
</body>
</html>

orders/templates/orders/order-create.html
{% extends 'languages/base.html' %}

{% block content %}

<div style="display: flex; flex-direction: column; align-items: center; text-align: center;">

    <div style="margin-top: 20px;">
        <strong>Please fill in your email address.</strong>
    </div>

    <div>
        <div>
            <h1>Checkout order</h1>
        </div>
        <div style="display: flex; justify-content: center;">

            <div style="margin-right: 20px;">
                <div style="background-color: #f0f0f0; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
                    padding: 20px; text-align: center; max-width: 400px;">
                    <h4 style="color: #333;">К оплате</h4>
                    <ul style="list-style: none; padding: 0; margin-top: 10px;">
                        {% for paid_card in paid_cards %}
                            <li style="border-bottom: 1px solid #ddd; padding: 10px 0;">

                                <div style="display: flex; justify-content: space-between; align-items: center; text-align: left;">
                                    <div>
                                        <h6 style="color: #333; margin: 0;">{{ paid_card.paid_lesson.title }}</h6>
                                        <small style="color: #777;">{{ paid_card.paid_lesson.price }} руб.</small>
                                    </div>
                                    <span style="font-weight: bold; color: #555;">{{ paid_card.sum }} руб.</span>
                                </div>

                            </li>
                        {% endfor %}

                        <li style="padding: 10px 0;">
                            <span style="font-weight: bold; color: #555;">Amount payable</span>
                            <strong style="font-size: 20px; color: #333;">{{ paid_cards.price_all_products }} руб.</strong>
                        </li>
                    </ul>
                </div>
            </div>

            <div>
                <div style="background-color: #f9f9f9; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); padding: 20px; text-align: center; max-width: 400px;">
                    <h4 style="color: #333;">Укажите данные и информацию о себе</h4>

                    <form action="{% url 'orders:order_create' %}" method="post">

                        {% csrf_token %}

                        <div style="margin-top: 15px; display: flex; flex-direction: column; align-items: center;">

                            <div style="margin-bottom: 15px; width: 100%;">
                                <label for="{{ form.first_name.id_for_label }}" style="display: block; color: #555; margin-bottom: 5px;">Name</label>
                                {{ form.first_name }}
                            </div>

                            <div style="margin-bottom: 15px; width: 100%;">
                                <label for="{{ form.last_name.id_for_label }}" style="display: block; color: #555; margin-bottom: 5px;">Surname</label>
                                {{ form.last_name }}
                            </div>

                            <div style="margin-bottom: 15px; width: 100%;">
                                <label for="{{ form.email.id_for_label }}" style="display: block; color: #555; margin-bottom: 5px;">Email Address</label>
                                {{ form.email }}
                            </div>
                        </div>

                        <hr style="border: 0.5px solid #ddd; margin: 20px 0;">

                        <button type="submit" style="background-color: #3498db; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">Next</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

orders/templates/orders/order.html
{% extends 'languages/base.html' %}
{% block content %}
<style>
    /* Добавленные стили для таблицы и параграфа */
.table {
    width: 100%;
    margin-bottom: 1rem;
    color: #212529;
}

.table th, .table td {
    padding: 0.75rem;
    vertical-align: top;
    border-top: 1px solid #dee2e6;
}

.table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #dee2e6;
}

.table tbody + tbody {
    border-top: 2px solid #dee2e6;
}

.table-bordered {
    border: 1px solid #dee2e6;
}

.table-bordered th, .table-bordered td {
    border: 1px solid #dee2e6;
}

.table-bordered thead th, .table-bordered thead td {
    border-bottom-width: 2px;
}

.table-hover tbody tr:hover {
    background-color: rgba(0, 123, 255, 0.05);
}

.float-right {
    float: right !important;
}

.mt-3 {
    margin-top: 1rem !important;
}

</style>
    <section>
        <div class="container mt-5">
            <div class="text-center mb-5">
                <h1 class="display-4">Order #{{ object.id }}</h1>
                <div class="orders mt-4">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Название</th>
                                    <th scope="col">Кол-во</th>
                                    <th scope="col">Цена</th>
                                    <th scope="col">Сумма</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for purchased_item in object.paid_card_history.purchased_items %}
                                    <tr>
                                        <th scope="row">
                                            {{ purchased_item.paid_lesson_name }}
                                        </th>
                                        <td>{{ purchased_item.quantity }}</td>
                                        <td>{{ purchased_item.price }} PLN</td>
                                        <td>{{ purchased_item.sum }} PLN</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <p class="float-right h4 mt-3"><strong>Итого {{ object.paid_card_history.total_sum }} PLN</strong></p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'languages/base.html' %}
{% block content %}
<style>
    /* Добавленные стили для таблицы и кнопки */
.table {
    width: 100%;
    margin-bottom: 1rem;
    color: #212529;
}

.table th, .table td {
    padding: 0.75rem;
    vertical-align: top;
    border-top: 1px solid #dee2e6;
}

.table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #dee2e6;
}

.table tbody + tbody {
    border-top: 2px solid #dee2e6;
}

.table-bordered {
    border: 1px solid #dee2e6;
}

.table-bordered th, .table-bordered td {
    border: 1px solid #dee2e6;
}

.table-bordered thead th, .table-bordered thead td {
    border-bottom-width: 2px;
}

.table-hover tbody tr:hover {
    background-color: rgba(0, 123, 255, 0.05);
}

.btn-primary {
    color: #fff;
    background-color: #007bff;
    border-color: #007bff;
}

.btn-primary:hover {
    color: #fff;
    background-color: #0056b3;
    border-color: #0056b3;
}

</style>
    <section>
        <div class="container mt-5">
            <div class="text-center mb-5">
                <h1 class="display-4">Заказы</h1>
                <div class="orders mt-4">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Статус</th>
                                    <th scope="col">Создан</th>
                                    <th scope="col">Итого</th>
                                    <th scope="col">Действие</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in object_list %}
                                    <tr>
                                        <th scope="row">{{ order.id }}</th>
                                        <td>{{ order.get_status_display }}</td>
                                        <td>{{ order.created }}</td>
                                        <td>{{ order.paid_card_history.total_sum }} PLN</td>
                                        <td>
                                            <a href="{% url 'orders:order' order.id %}" class="btn btn-primary">Просмотреть</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/success.html
{% extends 'languages/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Thank you for order!</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>
                                Your order has been successfully generated.
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}