basket/urls.py
from django.urls import path, include
from . import views

app_name = 'basket'

urlpatterns = [
    path('add_to_basket/<int:category_id>', views.add_to_basket, name='add_to_basket'),
    path('delete_basket_from_basket/<int:basket_id>/', views.delete_basket_from_basket, name='delete_basket_from_basket'),
]

chat/urls.py
from django.urls import path
from .views import chat_room

app_name = 'chat'

urlpatterns = [
    path('chat/', chat_room, name='chat_room'),
]

comments/urls.py
from django.urls import path, include
from . import views

app_name = 'comments'
urlpatterns = [
    path('language/<int:language_id>/add_comment_to_language/', views.add_comment_to_language, name='add_comment_to_language'),
    path('language/<int:language_id>/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

languages/urls.py
from django.urls import path
from . import views

app_name = 'languages'

urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='categories'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('new_category/', views.new_category, name='new_category'),
    path('<int:category_id>/new_language/', views.new_language, name='new_language'),
    path('category/<int:category_id>/edit_category/', views.edit_category, name='edit_category'),
    path('language/<int:language_id>/edit_language/', views.edit_language, name='edit_language'),
    path('category/<int:category_id>/language/<int:language_id>', views.language, name='language'),
    path('categories/<int:category_id>', views.delete_category, name='delete_category'),
    path('language/<int:language_id>', views.delete_language, name='delete_language'),
    path('delete_all_categories/', views.delete_all_categories, name='delete_all_categories'),
    path('delete_all_languages/<int:language_id>', views.delete_all_languages, name='delete_all_languages'),
    path('delete_category/', views.delete_with_choose_category, name='delete_with_choose_category'),
    path('all_languages/<int:category_id>/', views.all_languages, name='all_languages'),
    path('choose_studies/', views.choose_studies, name='choose_studies'),
]

opinions/urls.py
from django.urls import path, include
from . import views

app_name = 'opinions'

urlpatterns = [
    path('opinions/', views.opinions, name='opinions'),
    path('add_opinion/', views.add_opinion, name='add_opinion'),
    path('delete_opinion/<int:opinion_id>', views.delete_opinion, name='delete_opinion'),
]

programming_guide/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('languages.urls', 'languages')),
    path('users/', include('users.urls', 'users')),
    path('comments/', include('comments.urls', 'comments')),
    path('basket/', include('basket.urls', 'basket')),
    path('opinions/', include('opinions.urls', 'opinions')),
    path('chat/', include('chat.urls', 'chat')),
    path('paid_lessons/', include('paid_lessons.urls', 'paid_lessons')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('my_account/', views.account, name='my_account'),
    path('edit_account/', views.edit_account, name='edit_account'),
    path('list_users/', views.list_users, name='list_users'),
]

languages/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=25000, unique=True)
    image = models.ImageField(upload_to='media/image/', blank=True, null=True)
    views = models.PositiveIntegerField(default=0)

    class Meta:
        """In this class,
        we sort by name and correctly set the name in the admin panel"""
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def increment_views(self):
        self.views += 1
        self.save()

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/image/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        """In this class,
         we sort by name and correctly set the name in the admin panel"""
        ordering = ('name',)
        verbose_name = 'Language'
        verbose_name_plural = 'Languages'

    def __str__(self):
        """Return a string representation of the name
        for in the admin panel"""
        return str(self.name)

languages/forms.py
from django import forms
from languages.models import Category, Language


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'image']
        widgets = {'description': forms.Textarea(attrs={'cols': 80})}


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = ['name', 'description', 'image']
        widgets = {'description': forms.Textarea(attrs={'cols': 80})}

languages/views.py
from django.core import paginator
from django.core.paginator import PageNotAnInteger
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from comments.forms import CommentForm
from comments.models import Comments
from languages import forms
from languages.models import Category, Language


def index(request):
    return render(request, 'languages/index.html')


def categories(request):
    categories_list = Category.objects.all()
    categories_per_page = 9
    paginator = Paginator(categories_list, categories_per_page)
    page = request.GET.get('page')
    try:
        categories_page = paginator.page(page)
    except PageNotAnInteger:
        categories_page = paginator.page(1)
    except EmptyPage:
        categories_page = paginator.page(paginator.num_pages)

    context = {'categories_page': categories_page}
    return render(request, 'languages/categories.html', context)


def all_languages(request, category_id):
    category_id = Category.objects.get(id=category_id)
    languages_list = Language.objects.filter(category=category_id).order_by('created')
    languages_per_page = 3
    paginator = Paginator(languages_list, languages_per_page)
    page = request.GET.get('page')
    try:
        languages_page = paginator.page(page)
    except PageNotAnInteger:
        languages_page = paginator.page(1)
    except EmptyPage:
        languages_page = paginator.page(paginator.num_pages)
    list_languages = Language.objects.all()
    context = {'languages_page': languages_page}
    return render(request, 'languages/all_languages.html', context)


def category(request, category_id):
    category = Category.objects.get(id=category_id)
    category.increment_views()
    context = {'category': category}
    return render(request, 'languages/category.html', context)


def new_category(request):
    if request.method != 'POST':
        form = forms.CategoryForm()
    else:
        form = forms.CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('languages:categories')
    context = {'form': form}
    return render(request, 'languages/new_category.html', context)


def new_language(request, category_id):
    category = Category.objects.get(id=category_id)
    if request.method != 'POST':
        form = forms.LanguageForm()
    else:
        form = forms.LanguageForm(request.POST, request.FILES)
        if form.is_valid():
            new_lang = form.save(commit=False)
            new_lang.category = category
            new_lang.save()
            return redirect('languages:category', category_id=category.id)
    context = {'category': category, 'form': form}
    return render(request, 'languages/new_language.html', context)


def edit_category(request, category_id):
    category = Category.objects.get(id=category_id)
    if request.method != 'POST':
        form = forms.CategoryForm(instance=category)
    else:
        form = forms.CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            return redirect('languages:category', category_id=category.id)
    context = {'category': category, 'form': form}
    return render(request, 'languages/edit_category.html', context)


def edit_language(request, language_id):
    language = Language.objects.get(id=language_id)
    if request.method != 'POST':
        form = forms.LanguageForm(instance=language)
    else:
        form = forms.LanguageForm(request.POST, request.FILES, instance=language)
        if form.is_valid():
            form.save()
            return redirect('languages:category', language.category.id)
    context = {'language': language, 'form': form}
    return render(request, 'languages/edit_language.html', context)


def language(request, category_id, language_id):
    language = Language.objects.get(id=language_id)
    category = language.category.id
    comments = Comments.objects.filter(language=language)
    commentForm = CommentForm()
    context = {'language': language, 'category': category, 'comments': comments, 'commentForm': commentForm}
    return render(request, 'languages/language.html', context)


def delete_category(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    return redirect('languages:categories')


def delete_language(request, language_id):
    language = Language.objects.get(id=language_id)
    language.delete()
    return redirect('languages:category', id=language.category.id)


def delete_all_categories(request):
    categories = Category.objects.all()
    categories.delete()
    return redirect('languages:categories')


def delete_all_languages(request, category_id):
    languages = Category.objects.all()
    languages.delete()
    return redirect('languages:categories', id=category.id)


def delete_with_choose_category(request):
    template_name = 'languages/categories.html'  # Замените на ваш шаблон
    model = Category  # Замените на вашу модель данных
    category_id = request.POST.get('category_id')  # Получаем ID категории из формы
    try:
        category = model.objects.get(pk=category_id)
        category.delete()  # Удаляем категорию из базы данных
    except model.DoesNotExist:
        pass  # Обработка случая, когда категория не найдена
    return redirect('languages:categories')


def choose_studies(request):
    return render(request, 'languages/choose_studies.html')

languages/templates/languages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Website</title>
    <link rel="stylesheet" href="{% static 'css/styles_main.css' %}">
</head>
{% include 'languages/header__BASE.html '%}
{% block content %}
{% endblock content %}

    <footer style="background-color: black;">
        <p>&copy; 2023 Your Website Name</p>
    </footer>
</body>
</html>

languages/templates/languages/categories__buttons__settings.html
{% load static %}
{% if user.is_superuser or user.is_staff %}
<style>
    .settings-container {
        position: fixed;
        top: 100px;
        right: 10px;
        background-color: #3498db;
        border-radius: 10px;
        padding: 4px;
    }

    .settings-menu {
        text-align: right;
    }

    .settings-menu-btn {
        padding: 8px 12px;
        text-decoration: none;
        display: block;
        color: #fff;
        cursor: pointer;
        font-weight: bold;
        font-size: 14px;
    }

    .settings-menu-btn:hover {
        color: #eee;
    }

    .settings-menu-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 120px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        border-radius: 4px;
        right: 0;
    }

    .settings-menu-content a {
        padding: 8px 12px;
        text-decoration: none;
        display: block;
        color: #333;
        cursor: pointer;
        font-size: 14px;
    }

    .settings-menu-content a:hover {
        background-color: #ddd;
    }

    .settings-menu:hover .settings-menu-content {
        display: block;
    }

    .modal {
        display: none;
    }

    .modal button {
        padding: 8px 12px;
        margin-right: 8px;
        cursor: pointer;
        border: none;
        border-radius: 4px;
        font-size: 14px;
    }

    .modal button[type="submit"] {
        background-color: #2ecc71;
        color: #fff;
    }

    .modal button[type="submit"]:hover {
        background-color: #27ae60;
    }

    .modal button[type="button"] {
        background-color: #3498db;
        color: #fff;
    }

    .modal button[type="button"]:hover {
        background-color: #2980b9;
    }
</style>

<div class="settings-container">
    <div class="settings-menu">
        <div class="settings-menu-btn">Настройки</div>
        <div class="settings-menu-content">
            <a href="{% url 'languages:new_category' %}" class="menu-item">Новая категория</a>
            <div class="menu-item" onclick="openModal()">Удалить категорию</div>
        </div>
    </div>
</div>

<div class="modal" id="deleteModal" style="font-size: 14px; font-family: 'Source Code Pro', monospace; text-shadow: 1px 1px 1px black; text-align: right;">
    <p>Выберите категорию для удаления:</p>
    <form method="post" action="{% url 'languages:delete_with_choose_category' %}">
        {% csrf_token %}
        <select name="category_id" id="categorySelect">
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <input type="hidden" name="selected_category_id" id="selectedCategoryId">
        <button type="submit" onclick="setSelectedCategoryId()">Удалить</button>
        <button type="button" onclick="closeModal()">Отмена</button>
    </form>
</div>

<script>
    function openModal() {
        document.getElementById('deleteModal').style.display = 'block';
    }

    function closeModal() {
        document.getElementById('deleteModal').style.display = 'none';
    }

    function setSelectedCategoryId() {
        var selectedCategory = document.getElementById('categorySelect').value;
        document.getElementById('selectedCategoryId').value = selectedCategory;
    }
</script>
{% else %}
{% endif %}

languages/templates/languages/category.html
{% extends 'languages/base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ category.name }} Languages</title>
</head>
<style>
    body, html {
        margin: 0;
        padding: 0;
    }

    .btn-container {
        width: 250px;
        height: 250px;
        animation: shake 6s infinite;
        animation-timing-function: ease-in-out;
    }

    @keyframes shake {
        0%, 100% {
            transform: translateX(0) rotate(0) scale(1);
        }
        25% {
            transform: translateX(-5px) rotate(-5deg) scale(1.1);
        }
        50% {
            transform: translateX(5px) rotate(5deg) scale(0.9);
        }
        75% {
            transform: translateX(-5px) rotate(-5deg) scale(1.1);
        }
    }

    .description-block {
        max-width: 1400px;
        margin: 20px auto;
        padding: 20px;
        background-color: #f9f9f9;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        text-align: left;
        line-height: 1.5;
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
    }

    .language-block {
        background-color: rgba(255, 255, 255, 0.7);  /* Прозрачный белый цвет */
        border: 1px solid #ddd;
        border-radius: 5px;
        margin: 10px;
        padding: 10px;
        transition: all 0.3s ease;  /* Плавный переход при изменении размера */
    }

    .language-block:hover {
        transform: scale(1.1);  /* Увеличение размера при наведении */
    }

    .language-block a {
        text-decoration: none;
        color: #333;
    }

    .language-block img {
        width: 50px;
        height: 50px;
        margin-top: 5px;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropbtn {
        background-color: #3498db;
        color: white;
        padding: 10px;
        font-size: 16px;
        border-radius: 10px;
        cursor: pointer;
    }

    .dropdown-content {
        text-align: center;
        display: none;
        position: absolute;
        background-color: blue;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {
        background-color: #f1f1f1;
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .pagination {
        margin-top: 20px;
        text-align: center;
    }

    .step-links {
        display: inline-block;
        margin-right: 10px;
    }

    .step-links a {
        color: #333;
        text-decoration: none;
        padding: 8px 12px;
        border: 1px solid #ddd;
        margin-right: 5px;
    }

    .step-links a:hover {
        background-color: #000000;
    }

    .current {
        font-weight: bold;
        padding: 8px 12px;
        border: 1px solid #ddd;
        background-color: #007bff;
        color: #fff;
        margin-right: 5px;
    }

    .current:hover {
        background-color: #007bff;
    }

    .step-links a:disabled,
    .current:disabled {
        color: #aaa;
        pointer-events: none;
    }

    /* Опционально: стили для адаптивности */
    @media (max-width: 768px) {
        .step-links a,
        .current {
            display: block;
            width: 100%;
            margin-bottom: 5px;
        }
    }
        .button-container {
            display: flex;
            margin: 20px 0; /* Внешние отступы вокруг контейнера */
            background-image: url('/static/image/super_font.jpg');
            border-radius: 5px;
        }

        /* Стили для ссылки <a> внутри контейнера */

        .styled-button {
            display: inline-block;
            padding: 15px 30px;
            font-size: 16px;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
            background-color: #3498db;
            color: #fff;
            border-radius: 5px;
            border: 2px solid #2980b9;
            transition: background-color 0.3s ease;
            cursor: pointer;
        }

        .styled-button:hover {
            background-color: #2980b9;
        }
</style>


<body style="background-image: url('/static/image/super_font.jpg');">
    <div style="text-align: center; color: white">
        <div id="caption" style="margin-top: 20px;">
            <h1>Добро пожаловать в базовый курс такого замечательного языка как {{ category.name }}!</h1>
            {% if user.is_superuser or user.is_staff %}
                 <div class="dropdown" style="position: fixed; top: 100px; right: 10px;">
                    <button class="dropbtn" style="text-align: right;">Настройки</button>
                    <div class="dropdown-content">
                        <a href="{% url 'languages:edit_category' category.id %}">Edit</a>
                        <a href="{% url 'languages:new_language' category.id %}">Add</a>
                        <a href="{% url 'languages:categories' %}">Back</a>
                    </div>
                </div>
            {% endif %}
        </div>
        <img class="btn-container" src="{{ category.image.url }}" alt="{{ category.title }}">
        <div class="description-block">
            <h1 style="color: black;">Что такое {{ category.name }}?</h1>
            <p style="color: black;">{{ category.description }}</p>
            <a href="{% url 'languages:all_languages' category.id %}" class="styled-button">Начать обучение</a>
        </div>

        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
</body>
</html>
{% endblock content %}

languages/templates/languages/header__BASE.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>
    <style>
        header.navbar {
            background-color: rgba(0, 0, 0, 0.1);
            color: white;
            padding: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            transition: background-color 0.3s ease-in-out;
        }

        nav ul {
            margin: 0;
            padding: 0;
            list-style: none;
            display: flex;
        }

        li {
            margin-right: 20px;
            background-color: transparent;
            border: 2px solid white; /* Белая граница */
            border-radius: 3px;
            padding: 10px 20px; /* Задаем отступы внутри кнопки */
            display: flex;
            align-items: center;
            position: relative;
            transition: transform 0.3s ease-in-out, color 0.3s ease-in-out;
        }

        li a {
            color: white;
            text-decoration: none;
            width: 100%; /* Растягиваем ссылку на всю ширину кнопки */
            text-align: center;
        }

        li:hover {
            color: #001d3d; /* Темно-синий цвет при наведении */
            transform: scale(1.1); /* Увеличение размера при наведении */
        }
/* Стили для основного элемента dropdown */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Стили для ссылки внутри dropdown */
.dropdown a {
  text-decoration: none;
  color: #333; /* Цвет текста */
  padding: 10px 20px; /* Отступы вокруг текста */
  display: inline-block;
}

/* Стили для стрелки вниз */
.dropdown .caret {
  border-top: 6px solid white; /* Цвет стрелки */
  border-right: 6px solid transparent;
  border-left: 6px solid transparent;
  display: inline-block;
  vertical-align: middle;
  margin-left: 5px; /* Отступ от текста */
}

/* Стили для выпадающего меню */
.dropdown-menu {
  display: none; /* Начинаем с скрытого состояния */
  position: absolute;
  top: 100%; /* Отступ от верхней границы родительского элемента */
  left: 0; /* Выравниваем по левому краю родительского элемента */
  background-color: None; /* Цвет фона */
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Тень */
  z-index: 1;
}

/* Стили для элементов внутри выпадающего меню */
.dropdown-menu li {
  margin-left: 0; /* Обновленный отступ слева */
  padding: 10px 10px;
}

/* Изменяем стили при наведении на элемент внутри выпадающего меню */
.dropdown-menu li:hover {
  background-color: None; /* Цвет фона при наведении */
}
/* Показываем выпадающее меню при наведении на основной элемент */
.dropdown:hover .dropdown-menu {
  display: block;
}

/* Стили для ссылок внутри выпадающего меню */
.dropdown-menu a {
  text-decoration: none;
  color: #333; /* Цвет текста */
}
</style>
</head>
<body>
    <header class="navbar">
        <div class="logo">
            <a href="{% url 'languages:index' %}"><img src="{% static 'image/Astro-Logo.png' %}" class="logo-image"></a>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'languages:index' %}">Engineering Manager</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color: white; padding-left: 5px;">Your account<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'chat:chat_room' %}" style=" color: white; padding: 38px 38px;">Chat</a></li>
                        <li><a href="{% url 'users:list_users' %}" style=" color: white; padding: 38px 38px;">All Users</a></li>
                        <li><a href="{% url 'languages:choose_studies' %}" style=" color: white; padding: 38px 38px;">Studies</a></li>
                        <li><a href="{% url 'opinions:opinions' %}" style=" color: white; padding: 38px 38px;">Opinions</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color: white; padding-left: 5px;">Your account<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'users:my_account' %}" style="display: flex; align-items: center; color: white;">
                            Hello, {{ user.username }}
                            {% if not user.image %}
                                <img src="{% static 'image/user_account/default_avatar.jpg' %}" width="50px" height="50px" style="border-radius: 50px; margin-left: 10px;">
                            {% else %}
                                <img src="{{ user.image.url }}" width="50px" height="50px" style="border-radius: 50px; margin-left: 10px;">
                            {% endif %}
                        </a>
                    </li>
                    <li><a href="{% url 'users:logout' %}" style="color: white;">LogOut</a></li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}" style="color: white; padding: 30px 30px;">Login</a></li>
                        <li><a href="{% url 'users:register' %}" style="color: white; margin-left: 0px; padding: 48px 48px;">Register</a></li>
                    {% endif %}
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
</body>
</html>

languages/templates/languages/language.html
{% extends 'languages/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}
<style>
    .comment {
        border: 1px solid #ddd;
        padding: 15px;
        margin-bottom: 15px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    }

    .comment-user {
        color: #007bff;
        font-weight: bold;
    }

    .comment-text {
        font-size: 16px;
        color: #333;
    }

    .comment-created-at {
        color: #888;
        font-size: 12px;
    }

    .description-block {
        max-width: 1400px;
        margin: 20px auto;
        padding: 20px;
        background-color: #f9f9f9;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        text-align: left;
        line-height: 1.5;
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
    }

    .opinion-block {
        max-width: 1000px;
        margin: auto;
        margin-top: 20px;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .add-comment-section {
        text-align: center;
        margin-top: 30px;
    }

    .add-comment-title {
        color: #333;
        font-size: 18px;
        font-weight: bold;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        margin-bottom: 5px;
        color: #333;
        font-weight: bold;
    }

    input[type="text"],
    textarea {
        width: 95%;
        padding: 8px;
        border-top: 1px solid #ccc;
        border-right: none;
        border-bottom: 1px solid #ccc;
        border-left: none;
        border-radius: 1px;
        margin-bottom: 10px;

    }

    .submit-button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 1em;
        margin-left: 5px;
    }

    .submit-button:hover {
        background-color: #45a049;
    }

    .btn-styles {
        display: inline-block;
        padding: 8px 16px;
        margin: 5px;
        margin-left: 40px;
        text-decoration: none;
        color: #fff;
        background-color: #00bcd4;
        border-radius: 4px;
        transition: background-color 0.3s ease;
    }

    .btn-styles:hover {
        background-color: #008ba3;
    }

    .delete-link {
        color: #f00;
        text-decoration: none;
        margin-left: 10px;
    }

    .delete-link:hover {
        text-decoration: underline;
    }

</style>
<body style="background-image: url('/static/image/super_font.jpg');">
  <div class="description-block">
      <h2>{{ language.name }}</h2><br>
        {{ language.description }}
    {% if language.image %}
      <img src="{{ language.image.url }}" alt="{{ language.title }}" width="50px" height="50px">
    {% else %}
      No image available
    {% endif %}
  </div>
  {% if user.is_superuser or user.is_staff %}
    <a href="{% url 'languages:edit_language' language.id %}" class="btn-styles">Edit language</a>
    <a href="{% url 'languages:delete_language' language.id %}" class="btn-styles">Delete language</a>
  {% endif %}
 <div class="opinion-block" style="background-color: white;">
     <h2 style="text-align: center; color: black;">Комментарии к уроку</h2>
    {% for comment in comments %}
        <div class="comment">
            <h4 class="comment-user">user [{{ comment.user }}]</h4>
            <p class="comment-text">{{ comment.text }}</p>
            <span class="comment-created-at">{{ comment.created_at }}</span>
            <a class="delete-link" href="{% url 'comments:delete_comment' comment.language.id comment.id %}">Delete</a>
        </div>
    {% endfor %}

     <form class="add-comment-section" action="{% url 'comments:add_comment_to_language' language.id %}" method="post">
        {% csrf_token %}
        <div class="add-comment-title" style="margin-bottom: 2px;">Add your comment</div>
         {{ commentForm.text }}
        <button class="submit-button" type="submit" style="margin-left: 890px;">Send</button>
    </form>

</div>
</body>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}