chat/urls.py
from django.urls import path
from .views import chat_room

app_name = 'chat'

urlpatterns = [
    path('chat/', chat_room, name='chat_room'),
]

paid_lessons/urls.py
from django.urls import path
from . import views

app_name = 'paid_lessons'

urlpatterns = [
    path('add_paid_lesson/<int:user_id>', views.add_paid_lesson, name='add_paid_lesson'),
    path('list_paid_lesson/<int:user_id>', views.list_paid_lesson, name='list_paid_lesson'),
    path('show_lesson/<int:lesson_id>', views.show_lesson, name='show_lesson'),
    path('add_chapter/<int:lesson_id>', views.add_chapter, name='add_chapter'),
    path('all_paid_lessons/', views.all_paid_lessons, name='all_paid_lessons'),
]

programming_guide/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('languages.urls', 'languages')),
    path('users/', include('users.urls', 'users')),
    path('comments/', include('comments.urls', 'comments')),
    path('basket/', include('basket.urls', 'basket')),
    path('opinions/', include('opinions.urls', 'opinions')),
    path('chat/', include('chat.urls', 'chat')),
    path('paid_lessons/', include('paid_lessons.urls', 'paid_lessons')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paid_lessons/models.py
from django.db import models
from django.db import models
from programming_guide.settings import AUTH_USER_MODEL


class PaidLesson(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок урока')
    description = models.TextField(verbose_name='Описание урока')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    duration = models.DurationField(verbose_name='Длительность урока')
    date_published = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    teacher = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Преподаватель')
    video_url = models.FileField(upload_to='media/paid_lessons_video', blank=True, null=True,
                                 verbose_name='Ссылка на видео')

    def __str__(self):
        return self.title


class PaidСhapter(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок раздела')
    lesson = models.ForeignKey(PaidLesson, on_delete=models.CASCADE)
    description = models.TextField(verbose_name='Описание раздела')
    duration = models.DurationField(verbose_name='Длительность раздела')
    date_published = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    video_url = models.FileField(upload_to='media/paid_lessons_video', blank=True, null=True,
                                 verbose_name='Ссылка на видео')

    def __str__(self):
        return self.title

paid_lessons/forms.py
from django import forms
from paid_lessons.models import PaidLesson, PaidСhapter


class PaidLessonForm(forms.ModelForm):
    class Meta:
        model = PaidLesson
        fields = ['title', 'description', 'price', 'duration', 'video_url', ]
        widgets = {'description': forms.Textarea(attrs={'cols': 64})}


class AddChapterForm(forms.ModelForm):
    class Meta:
        model = PaidСhapter
        fields = ['title', 'description', 'duration', 'video_url', ]
        widgets = {'description': forms.Textarea(attrs={'cols': 64})}

paid_lessons/views.py
from django.shortcuts import render, redirect
from paid_lessons.forms import PaidLessonForm, AddChapterForm
from paid_lessons.models import PaidLesson, PaidСhapter
from programming_guide.settings import AUTH_USER_MODEL
from users.models import User


def add_paid_lesson(request, user_id):
    if request.method != 'POST':
        form = PaidLessonForm()
    else:
        form = PaidLessonForm(data=request.POST)
        if form.is_valid():
            user_form = form.save(commit=False)
            user = User.objects.get(id=user_id)
            user_form.teacher = user
            user_form.save()
            return redirect('paid_lessons:list_paid_lesson', user_id=user_id)
    context = {'form': form}
    return render(request, 'paid_lessons/add_paid_lesson.html', context)


def list_paid_lesson(request, user_id):
    lessons = PaidLesson.objects.filter(teacher=user_id)
    context = {'lessons': lessons}
    return render(request, 'paid_lessons/list_paid_lesson.html', context)


def all_paid_lessons(request):
    paid_lessons = PaidLesson.objects.all()
    context = {'paid_lessons': paid_lessons}
    return render(request, 'paid_lessons/all_paid_lessons.html', context)


def show_lesson(request, lesson_id):
    chapters = PaidСhapter.objects.filter(lesson=lesson_id)
    context = {'chapters': chapters}
    return render(request, 'paid_lessons/paid_lesson.html', context)


def add_chapter(request, lesson_id):
    lesson = PaidLesson.objects.get(id=lesson_id)
    if request.method != 'POST':
        form = AddChapterForm()
    else:
        form = AddChapterForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.lesson = lesson
            form.save()
            return redirect('paid_lessons:show_lesson', lesson.id)
    context = {'lesson': lesson, 'form': form}
    return render(request, 'paid_lessons/add_chapter.html', context)

paid_lessons/templates/paid_lessons/add_chapter.html
{% extends 'languages/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        form {
            max-width: 700px;
            max-height: 540px;
            background-color: #fff;
            justify-content: center;
            padding: 10px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input {
            width: 70%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body style="background-image: url('/static/image/super_font.jpg');">
    <form action="{% url 'paid_lessons:add_chapter' lesson.id %}" method="post" enctype="multipart/form-data" style="margin-left: 200px;">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Submit</button>
    </form>
</body>
</html>
{% endblock content %}

paid_lessons/templates/paid_lessons/add_paid_lesson.html
{% extends 'languages/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            background-image: url('/static/image/super_font.jpg');
            font-family: Arial, sans-serif; /* Шрифт по умолчанию */
            margin: 0; /* Убираем внешние отступы у body */
            padding: 20px; /* Добавляем внутренние отступы для формы */
        }

        form {
            max-width: 400px; /* Максимальная ширина формы */
            margin: 0 auto; /* Центрируем форму по горизонтали */
            background-color: #ffffff; /* Цвет фона формы */
            padding: 20px; /* Внутренние отступы для формы */
            border-radius: 8px; /* Закругляем углы формы */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Тень формы */
        }

        label {
            display: block;
            margin-bottom: 8px; /* Отступ снизу метки */
        }

        input, textarea {
            width: 100%;
            padding: 8px; /* Внутренние отступы для текстовых полей */
            margin-bottom: 16px; /* Отступ снизу текстовых полей */
            box-sizing: border-box; /* Учитываем границы и отступы внутри ширины */
        }

        button {
            background-color: #4CAF50; /* Цвет фона кнопки */
            color: #ffffff; /* Цвет текста кнопки */
            padding: 10px 15px; /* Внутренние отступы кнопки */
            border: none; /* Убираем границу кнопки */
            border-radius: 4px; /* Закругляем углы кнопки */
            cursor: pointer; /* Изменяем курсор при наведении на кнопку */
        }

        button:hover {
            background-color: #45a049; /* Цвет фона кнопки при наведении */
        }
    </style>
</head>
<body>
    <form action="{% url 'paid_lessons:add_paid_lesson' request.user.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-button">Save</button>
    </form>
</body>
</html>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

paid_lessons/templates/paid_lessons/all_paid_lessons.html
{% extends 'languages/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-image: url('/static/image/super_font.jpg');">
<div style="text-align: center;">
    {% for paid_lesson in paid_lessons %}
        <a href="{% url 'paid_lessons:show_lesson' paid_lesson.id %}">
            <div style="background-color: white; padding: 20px; margin-bottom: 20px; display: inline-block;
                padding: 10px 20px; margin-top: 30px; border-radius: 10px;">
                <h2>{{ lesson.title }}</h2>
                <p><strong>Description:</strong> {{ paid_lesson.description }}</p>
                <p><strong>Price:</strong> ${{ paid_lesson.price }}</p>
                <p><strong>Duration:</strong> {{ paid_lesson.duration }}</p>
                <p><strong>Teacher: {{ paid_lesson.teacher.first_name }}</strong></p>
                {% if paid_lesson.video_url %}
                    <video width="320" height="240" controls>
                        <source src="{{ lesson.video_url.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                {% else %}
                    <p>No video file associated with this lesson.</p>
                {% endif %}
            </div>
        </a>
    {% endfor %}
</div>
</body>
</html>
{% endblock content %}

paid_lessons/templates/paid_lessons/list_paid_lesson.html
{% extends 'languages/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-image: url('/static/image/super_font.jpg');">
<div style="text-align: center;">
    {% for lesson in lessons %}
        <a href="{% url 'paid_lessons:show_lesson' lesson.id %}">
            <div style="background-color: white; padding: 20px; margin-bottom: 20px; display: inline-block;
                padding: 10px 20px; margin-top: 30px; border-radius: 10px;">
                <h2>{{ lesson.title }}</h2>
                <p><strong>Description:</strong> {{ lesson.description }}</p>
                <p><strong>Price:</strong> ${{ lesson.price }}</p>
                <p><strong>Duration:</strong> {{ lesson.duration }}</p>
                {% if lesson.video_url %}
                    <video width="320" height="240" controls>
                        <source src="{{ lesson.video_url.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                {% else %}
                    <p>No video file associated with this lesson.</p>
                {% endif %}
            </div>
        </a>
    {% endfor %}
</div>
</body>
</html>
<br>
<br>
<br>
<br>
{% endblock content %}

paid_lessons/templates/paid_lessons/paid_lesson.html
{% extends 'languages/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        .chapter-container {
            background-color: white;
            width: 700px;
            height: 400px;
            margin-bottom: 20px;
            margin-top: 30px;
            border-radius: 10px;
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            padding: 10px 20px;
            margin: 20px auto;
            background:
            linear-gradient(to right, #ffffff 50%, transparent 50%),
            url('/static/image/super_font.jpg');
            background-size: 100% 100%;
        }

        .text-container {
            flex: 1;
            margin-right: 55px;
            background-color: white;
            padding: 20px;
            border-radius: 5px;
            overflow: hidden;
            transition: height 0.3s ease;
        }

        .video-container {
            flex: 1;
            margin-right: 15px;
            border-radius: 5px;
            overflow: hidden;
        }

        .video-container video {
            width: 100%;
            height: 100%;
            border-radius: 5px;
        }

        .read-more {
            cursor: pointer;
            color: blue;
            display: block;
            margin-top: 10px;
        }
        .modal-body {
        word-wrap: break-word;
    }
    </style>
</head>
<body style="background-image: url('/static/image/super_font.jpg');">
<div style="text-align: center;">
    <h1 style="color: white;">Уроки по {{ chapters.first.lesson.title }}</h1>
    {% for chapter in chapters %}
        <div class="chapter-container" style="border: 1px solid black; box-shadow: 2px 2px 5px rgba(2, 2, 2, 2);">
            <div class="text-container" id="textContainer{{ chapter.id }}">
                <p style="color: black;">Название раздела: <strong>{{ chapter.title }}</strong></p>
                <p style="color: black;">Описание: <span id="description{{ chapter.id }}">{{ chapter.description }}</span>
                    {% if chapter.description|length > 50 %}
                        <span class="read-more" onclick="toggleDescription({{ chapter.id }})">Читать далее</span>
                    {% endif %}
                </p>
                <p style="color: black;">Время урока: <strong>{{ chapter.duration }}</strong></p>
            </div>
            <div class="video-container">
                {% if chapter.video_url %}
                    <p><strong style="color: black;">Урок</strong></p>
                    <video width="100%" height="100%" controls style="border: 1px solid black;">
                        <source src="{{ chapter.video_url.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                {% else %}
                    <p>No video file associated with this chapter.</p>
                {% endif %}
            </div>
        </div>
    {% endfor %}


<div class="modal fade" id="descriptionModal" tabindex="-1" role="dialog" aria-labelledby="descriptionModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="max-width: 80%;" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="descriptionModalLabel">Подробное описание</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="descriptionModalBody"></div>
        </div>
    </div>
</div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script>
        function toggleDescription(chapterId) {
            var description = document.getElementById('description' + chapterId).innerText;
            document.getElementById('descriptionModalBody').innerText = description;
            $('#descriptionModal').modal('show');
        }
    </script>
</div>

</body>
</html>
<br>
<br>
<br>
<br>
{% endblock content %}