chat/urls.py
from django.urls import path
from .views import chat_room

app_name = 'chat'

urlpatterns = [
    path('chat/', chat_room, name='chat_room'),
]

opinions/urls.py
from django.urls import path, include
from . import views

app_name = 'opinions'

urlpatterns = [
    path('opinions/', views.opinions, name='opinions'),
    path('add_opinion/', views.add_opinion, name='add_opinion'),
    path('delete_opinion/<int:opinion_id>', views.delete_opinion, name='delete_opinion'),
]

programming_guide/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('languages.urls', 'languages')),
    path('users/', include('users.urls', 'users')),
    path('comments/', include('comments.urls', 'comments')),
    path('basket/', include('basket.urls', 'basket')),
    path('opinions/', include('opinions.urls', 'opinions')),
    path('chat/', include('chat.urls', 'chat')),
    path('paid_lessons/', include('paid_lessons.urls', 'paid_lessons')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opinions/models.py
from django.db import models
from users.models import User


class Opinion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1500)
    rating = models.IntegerField(
        choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

opinions/forms.py
from django import forms

from opinions.models import Opinion


class OpinionForm(forms.ModelForm):
    class Meta:
        model = Opinion
        fields = ['text', 'rating', ]
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
            'rating': forms.Select(
                choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')]), }

opinions/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from opinions.forms import OpinionForm
from opinions.models import Opinion
from users.models import User


def opinions(request):
    opinions = Opinion.objects.all()
    context = {'opinions': opinions}
    return render(request, 'opinions/opinions.html', context)


def add_opinion(request):
    rating = request.POST.get('rating', None)
    if request.method != 'POST':
        form = OpinionForm()
    else:
        form = OpinionForm(data=request.POST)
        if form.is_valid():
            opinion = form.save(commit=False)
            opinion.user = request.user
            opinion.save()
            return redirect('opinions:opinions')
    context = {'form': form, 'rating': rating}
    return render(request, 'opinions/add_opinion.html', context)


def delete_opinion(request, opinion_id):
    opinion = Opinion.objects.get(id=opinion_id)
    if request.user == opinion.user:
        opinion.delete()
        messages.success(request, 'Отзыв успешно удален.')
    else:
        messages.error(request, 'У вас нет прав для удаления этого отзыва.')
    return redirect('opinions:opinions')

opinions/templates/opinions/add_opinion.html
{% extends 'languages/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}
<style>
  /* Стилизация формы для оставления отзыва */
  form {
    text-align: center;
    margin: 20px auto;
    max-width: 600px;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }

  /* Стилизация полей ввода и кнопки */
  input[type="text"] {
    width: 100%;
    padding: 8px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    font-size: 16px;
  }

  .btn-button {
    background-color: #4CAF50;
    color: white;
    padding: 12px 24px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 18px;
  }

  .btn-button:hover {
    background-color: #45a049;
  }
</style>
<body>
  <form action="{% url 'opinions:add_opinion' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn-button">Оставить отзыв</button>
  </form>
</body>
</html>
{% endblock content %}

opinions/templates/opinions/opinions.html
{% extends 'languages/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
</head>

{% block content %}
<style>
.koguvcavis-varazdel {
  padding: 38px 0;
  background: #adadad;
  color: #2f2f2f;
  text-align: center;
  margin-bottom: 70px;
}
.sestim-donials{
  max-width: 1200px;
  margin: auto;
  overflow: hidden;
  padding: 0 20px;
}

.sectionesag {
  width: 195px;
  height: 3px;
  background: #498a2d;
  margin: 23px auto;
}

.sectionesag-2 {
  width: 180px;
  height: 3px;
  background: #498a2d;
  margin-left: 16px;
}


.add-opinion-button:hover {
  transform: scale(1.1); /* Увеличение размера при наведении */
}
.add-opinion-button:hover {
  box-shadow: 0 0 10px rgba(52, 152, 219, 0.7), inset 0 0 10px rgba(52, 152, 219, 0.7);
  /* Внешняя тень с подгоранием и внутренняя тень с подгоранием */
}
.button-container {
  text-align: center;
  margin-top: -5px;
  margin-bottom: 20px;
}

.add-opinion-button {
  display: inline-block;
  padding: 10px 20px;
  background-color: #3498db; /* Цвет фона кнопки */
  color: #ffffff; /* Цвет текста кнопки */
  text-decoration: none;
  border-radius: 5px; /* Округление уголков кнопки */
  font-size: 16px;
  transition: transform 0.3s ease, box-shadow 0.3s ease; /* Анимации для увеличения и подгорания */
}

.add-opinion-button:hover {
  transform: scale(1.1); /* Увеличение размера при наведении */
  box-shadow: 0 0 10px rgba(52, 152, 219, 0.7), inset 0 0 10px rgba(52, 152, 219, 0.7);
  /* Подгорание при наведении */
}



.delete-button-container {
  margin-left: 200px;
}

.delete-button {
  display: inline-block;
  padding: 8px 16px; /* Уменьшение размера кнопки */
  background-color: #e74c3c; /* Цвет фона кнопки */
  color: #ffffff; /* Цвет текста кнопки */
  text-decoration: none;
  border-radius: 5px; /* Округление уголков кнопки */
  font-size: 14px; /* Уменьшение размера шрифта */
  cursor: pointer; /* Изменение курсора при наведении */
  transition: transform 0.3s ease, box-shadow 0.3s ease; /* Анимации для эффектов */
}

.delete-button:hover {
  transform: scale(1.1); /* Увеличение размера при наведении */
  box-shadow: 0 0 10px rgba(231, 76, 60, 0.7); /* Тень при наведении */
}


.sagestim-lonials{
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between; /* Adjusted to space between items */
}
.vemotau-vokusipol{
  width: calc(30% - 10px); /* Определите размер блока с учетом отступов */
  box-sizing: border-box;
  padding: 15px;
  border-radius: 10px;
  margin-bottom: 20px;
  background-color: #f9f4f4; /* Цвет фона блока */
}
.testimonial {
  background: #f9f4f4;
  padding: 28px;
}
.testimonial img{
  width: 100px;
  height: 100px;
  border-radius: 50%;
}
.gecedanam{
  font-size: 20px;

  text-transform: uppercase;
  margin: 20px 0;
}
.apogered-gselected{
  color: #53b32b;
  margin-bottom: 20px;
}

@media screen and (max-width:960px) {
  .vemotau-vokusipol{
    width: 48%; /* Adjusted to make each item take up about half the container width */
    max-width: 48%;
  }
}

@media screen and (max-width:600px) {
  .vemotau-vokusipol{
    width: 100%; /* Adjusted to make each item take up the full container width */
    max-width: 100%;
  }
}
</style>
<body style="background-image: url('/static/image/super_font.jpg');">
  <h1 style="margin-top: 30px; margin-left: 30px; color: white;">ОТЗЫВЫ</h1>
  <div class="sectionesag-2"></div>
  <h4 style="margin-left: 16px; color: white;">Только благодаря каждому из Вас, мы становимся лучше. Учились на нашем сайте и Вам есть что сказать? Тогда оставьте отзыв.</h4>
  <div class="koguvcavis-varazdel" style="background-color: white;">

  <a href="{% url 'opinions:add_opinion' %}">
    <div class="button-container" style="text-align: center;">
      <div class="add-opinion-button">
        Добавить отзыв
      </div>
    </div>
  </a>

    <div class="sestim-donials">
      <div class="sagestim-lonials">
        {% for opinion in opinions %}
          <div class="vemotau-vokusipol">
            <div class="testimonial">
              {% if opinion.user.image %}
                <img src="{{ opinion.user.image.url }}" alt="">
              {% else %}
                <img src="{% static 'image/user_account/default_avatar.jpg' %}">
              {% endif %}
              <div class="gecedanam">{{ opinion.user.first_name }} {{ opinion.user.last_name }}</div>
              <p>{{ opinion.text }}</p>
              <p>{{ opinion.created_at }}</p>
              <p>Оценка: {{ opinion.rating }}</p>
                  {% if opinion.rating %}
                    <div>
                      {% for _ in "_"|rjust:opinion.rating %}
                        <img src="{% static 'image/star_rating.png' %}" style="width: 25px; height: 25px;">
                      {% endfor %}
                    </div>
                  {% endif %}
                <div class="delete-button-container">
                  <form method="post" action="{% url 'opinions:delete_opinion' opinion.id %}">
                      {% csrf_token %}
                      <button type="submit" class="delete-button">
                          Удалить
                      </button>
                  </form>
                </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</body>
{% endblock content %}
</html>